### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by AsielPosada** [Enkel-Digital/relativity#2]
What is the command for use?

**Comment by Jaimeloeuf** [comment]
Hello, sorry for the late reply.

If you are using windows, use alt + g to goto a relative line number and alt + s to goto a relative line number and selecting the text in between the 2 cursor points.

**Comment by Arthurgroll997** [comment]
It would be useful to have it in the README!

> Hello, sorry for the late reply.
> 
> If you are using windows, use alt + g to goto a relative line number and alt + s to goto a relative line number and selecting the text in between the 2 cursor points.
